name = "Statine"
license = "MIT"
licenselink = "https://gitlab.com/upbqdn/statine/-/blob/main/LICENSE.md"
description = "Yet another Hugo minimal theme"

homepage = "https://gitlab.com/upbqdn/statine"

demosite = "https://marek.onl/"

tags = ["blog", "minimal", "personal", "responsive", "dark"]
features = ["blog", "taxonomies", "privacy", "dark"]
min_version = 0.25

[author]
  name = "Marek"
  homepage = "https://marek.onl"

[original]
  name = "Hugo Cisneros"
  homepage = "https://hugocisneros.com/"
  repo = "https://github.com/hugcis/hugo-astatine-theme"
